# Generated by Django 2.2 on 2021-09-14 08:20

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bill', models.DecimalField(decimal_places=2, help_text='Total bill including all the items', max_digits=30, validators=[utils.check_positive])),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date and Time of the order')),
                ('status', models.CharField(default='Placed', help_text='Current Status of Order', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of single Item', max_digits=30, validators=[utils.check_positive])),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of items ordered')),
            ],
        ),
    ]
