# Generated by Django 2.2 on 2021-09-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210914_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='food_id',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], default='PLACED', help_text='Current Status of Order', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity of given item ordered'),
        ),
    ]
