# Generated by Django 2.2 on 2021-09-14 08:20

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20210914_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Restaurant name', max_length=100)),
                ('city', models.CharField(help_text='Restaurant city', max_length=30)),
                ('owners', models.ManyToManyField(to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Menu Item Name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Menu Item Price', max_digits=30, validators=[utils.check_positive])),
                ('description', models.CharField(blank=True, help_text='Menu Item Description', max_length=200)),
                ('quantity_available', models.PositiveIntegerField(help_text='Menu Item Quantity Available')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
