# Generated by Django 2.2 on 2021-09-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owners',
            field=models.ManyToManyField(related_name='restaurants', to='user.User'),
        ),
    ]
