# Generated by Django 2.2 on 2021-09-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210915_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
