# Generated by Django 2.2 on 2021-09-13 13:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Full Name', max_length=100)),
                ('email', models.EmailField(help_text='Enter Email ID', max_length=254)),
                ('city', models.CharField(help_text='Enter your current city', max_length=30)),
                ('state', models.CharField(help_text='Enter your current state', max_length=30)),
                ('zip', models.PositiveIntegerField(help_text='Enter Your Zip Code', validators=[user.models.check_positive])),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=30, validators=[user.models.check_positive])),
            ],
        ),
    ]
