# Generated by Django 2.2 on 2021-09-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip',
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.PositiveIntegerField(default=0, help_text="Zip Code of User's Address"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(help_text='Current City of User', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email ID of User', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Full Name of User', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(help_text='Current State of User', max_length=30),
        ),
    ]
