# Generated by Django 2.2 on 2021-09-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210914_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.PositiveIntegerField(help_text="Zip Code of User's Address"),
        ),
    ]
