# Generated by Django 2.2 on 2021-09-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
